# Generated by Django 5.2.4 on 2025-07-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todolist_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['id']},
        ),
    ]
